// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzIR-jSHGVqD9HgqxAjFCRQXy4BnANCTw',
    appId: '1:122964367363:web:8149baadbcfd1b08cf9636',
    messagingSenderId: '122964367363',
    projectId: 'twitterclone-41252',
    authDomain: 'twitterclone-41252.firebaseapp.com',
    databaseURL: 'https://twitterclone-41252-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'twitterclone-41252.firebasestorage.app',
    measurementId: 'G-P07YL2CMB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI5aIhWZ0FP42kUxbucSs8hQeyLkgejDE',
    appId: '1:122964367363:android:62ae7c4bc8ceaa80cf9636',
    messagingSenderId: '122964367363',
    projectId: 'twitterclone-41252',
    databaseURL: 'https://twitterclone-41252-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'twitterclone-41252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwg_ojxINte9_dGk8Szi8oybQdl_W2m14',
    appId: '1:122964367363:ios:8dc74a628530c7d1cf9636',
    messagingSenderId: '122964367363',
    projectId: 'twitterclone-41252',
    databaseURL: 'https://twitterclone-41252-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'twitterclone-41252.firebasestorage.app',
    androidClientId: '122964367363-3cb8qqnmh0njaimamqcm54qh01tt53up.apps.googleusercontent.com',
    iosClientId: '122964367363-a9hjkidl135ulcuctqgepicc6b7l0aof.apps.googleusercontent.com',
    iosBundleId: 'com.yashg.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwg_ojxINte9_dGk8Szi8oybQdl_W2m14',
    appId: '1:122964367363:ios:8dc74a628530c7d1cf9636',
    messagingSenderId: '122964367363',
    projectId: 'twitterclone-41252',
    databaseURL: 'https://twitterclone-41252-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'twitterclone-41252.firebasestorage.app',
    androidClientId: '122964367363-3cb8qqnmh0njaimamqcm54qh01tt53up.apps.googleusercontent.com',
    iosClientId: '122964367363-a9hjkidl135ulcuctqgepicc6b7l0aof.apps.googleusercontent.com',
    iosBundleId: 'com.yashg.twitterClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzIR-jSHGVqD9HgqxAjFCRQXy4BnANCTw',
    appId: '1:122964367363:web:4ad20560d9d7a6accf9636',
    messagingSenderId: '122964367363',
    projectId: 'twitterclone-41252',
    authDomain: 'twitterclone-41252.firebaseapp.com',
    databaseURL: 'https://twitterclone-41252-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'twitterclone-41252.firebasestorage.app',
    measurementId: 'G-BQ8MK4NL6D',
  );

}